package com.plip.persistence.models;

// Generated Dec 18, 2013 12:11:56 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * OrderImages generated by hbm2java
 */
public class OrderImages implements java.io.Serializable {

	private Long idOrderImages;
	private String path;
	private Set pages = new HashSet(0);

	public OrderImages() {
	}

	public OrderImages(String path) {
		this.path = path;
	}

	public OrderImages(String path, Set pages) {
		this.path = path;
		this.pages = pages;
	}

	public Long getIdOrderImages() {
		return this.idOrderImages;
	}

	public void setIdOrderImages(Long idOrderImages) {
		this.idOrderImages = idOrderImages;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Set getPages() {
		return this.pages;
	}

	public void setPages(Set pages) {
		this.pages = pages;
	}

}
