package com.plip.persistence.models;

// Generated Dec 18, 2013 12:11:56 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Page generated by hbm2java
 */
public class Page implements java.io.Serializable {

	private Long idPage;
	private Order order;
	private OrderImages orderImages;
	private Integer productQuantity;
	private int pageNumber;
	private Set trays = new HashSet(0);
	private Set pageProducts = new HashSet(0);

	public Page() {
	}

	public Page(Order order, OrderImages orderImages, int pageNumber) {
		this.order = order;
		this.orderImages = orderImages;
		this.pageNumber = pageNumber;
	}

	public Page(Order order, OrderImages orderImages, Integer productQuantity,
			int pageNumber, Set trays, Set pageProducts) {
		this.order = order;
		this.orderImages = orderImages;
		this.productQuantity = productQuantity;
		this.pageNumber = pageNumber;
		this.trays = trays;
		this.pageProducts = pageProducts;
	}

	public Long getIdPage() {
		return this.idPage;
	}

	public void setIdPage(Long idPage) {
		this.idPage = idPage;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public OrderImages getOrderImages() {
		return this.orderImages;
	}

	public void setOrderImages(OrderImages orderImages) {
		this.orderImages = orderImages;
	}

	public Integer getProductQuantity() {
		return this.productQuantity;
	}

	public void setProductQuantity(Integer productQuantity) {
		this.productQuantity = productQuantity;
	}

	public int getPageNumber() {
		return this.pageNumber;
	}

	public void setPageNumber(int pageNumber) {
		this.pageNumber = pageNumber;
	}

	public Set getTrays() {
		return this.trays;
	}

	public void setTrays(Set trays) {
		this.trays = trays;
	}

	public Set getPageProducts() {
		return this.pageProducts;
	}

	public void setPageProducts(Set pageProducts) {
		this.pageProducts = pageProducts;
	}

}
