package com.plip.persistence.models;

// Generated Dec 18, 2013 12:11:56 PM by Hibernate Tools 4.0.0

/**
 * PlipUser generated by hbm2java
 */
public class PlipUser implements java.io.Serializable {

	private Long idPlipUser;
	private PlipRoles plipRoles;
	private String name;
	private String lastName;
	private String username;
	private String password;

	public PlipUser() {
	}

	public PlipUser(PlipRoles plipRoles, String name, String lastName,
			String username, String password) {
		this.plipRoles = plipRoles;
		this.name = name;
		this.lastName = lastName;
		this.username = username;
		this.password = password;
	}

	public Long getIdPlipUser() {
		return this.idPlipUser;
	}

	public void setIdPlipUser(Long idPlipUser) {
		this.idPlipUser = idPlipUser;
	}

	public PlipRoles getPlipRoles() {
		return this.plipRoles;
	}

	public void setPlipRoles(PlipRoles plipRoles) {
		this.plipRoles = plipRoles;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
