package com.plip.persistence.models;

// Generated Dec 15, 2013 6:52:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * TrayStatusId generated by hbm2java
 */
public class TrayStatusId implements java.io.Serializable {

	private long trayIdTray;
	private int statusIdStatus;

	public TrayStatusId() {
	}

	public TrayStatusId(long trayIdTray, int statusIdStatus) {
		this.trayIdTray = trayIdTray;
		this.statusIdStatus = statusIdStatus;
	}

	public long getTrayIdTray() {
		return this.trayIdTray;
	}

	public void setTrayIdTray(long trayIdTray) {
		this.trayIdTray = trayIdTray;
	}

	public int getStatusIdStatus() {
		return this.statusIdStatus;
	}

	public void setStatusIdStatus(int statusIdStatus) {
		this.statusIdStatus = statusIdStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TrayStatusId))
			return false;
		TrayStatusId castOther = (TrayStatusId) other;

		return (this.getTrayIdTray() == castOther.getTrayIdTray())
				&& (this.getStatusIdStatus() == castOther.getStatusIdStatus());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getTrayIdTray();
		result = 37 * result + this.getStatusIdStatus();
		return result;
	}

}
