package com.plip.persistence.models;

// Generated Dec 15, 2013 6:52:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * UserTypes generated by hbm2java
 */
public class UserTypes implements java.io.Serializable {

	private int idUserType;
	private String description;
	private Set users = new HashSet(0);

	public UserTypes() {
	}

	public UserTypes(int idUserType, String description) {
		this.idUserType = idUserType;
		this.description = description;
	}

	public UserTypes(int idUserType, String description, Set users) {
		this.idUserType = idUserType;
		this.description = description;
		this.users = users;
	}

	public int getIdUserType() {
		return this.idUserType;
	}

	public void setIdUserType(int idUserType) {
		this.idUserType = idUserType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
