package com.plip.persistence.models;

// Generated Dec 15, 2013 6:52:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Long idUser;
	private UserTypes userTypes;
	private String name;
	private String lastName;
	private String username;
	private String password;

	public User() {
	}

	public User(UserTypes userTypes, String name, String lastName,
			String username, String password) {
		this.userTypes = userTypes;
		this.name = name;
		this.lastName = lastName;
		this.username = username;
		this.password = password;
	}

	public Long getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Long idUser) {
		this.idUser = idUser;
	}

	public UserTypes getUserTypes() {
		return this.userTypes;
	}

	public void setUserTypes(UserTypes userTypes) {
		this.userTypes = userTypes;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
