package com.plip.persistence.models;

// Generated Dec 15, 2013 8:06:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * UserTypes generated by hbm2java
 */
public class UserTypes implements java.io.Serializable {

	private Integer idUserType;
	private String description;
	private Set users = new HashSet(0);

	public UserTypes() {
	}

	public UserTypes(String description) {
		this.description = description;
	}

	public UserTypes(String description, Set users) {
		this.description = description;
		this.users = users;
	}

	public Integer getIdUserType() {
		return this.idUserType;
	}

	public void setIdUserType(Integer idUserType) {
		this.idUserType = idUserType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
