package com.plip.persistance.models;

// Generated Dec 15, 2013 7:23:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * PageProductId generated by hbm2java
 */
public class PageProductId implements java.io.Serializable {

	private long pageIdPage;
	private long productIdProduct;

	public PageProductId() {
	}

	public PageProductId(long pageIdPage, long productIdProduct) {
		this.pageIdPage = pageIdPage;
		this.productIdProduct = productIdProduct;
	}

	public long getPageIdPage() {
		return this.pageIdPage;
	}

	public void setPageIdPage(long pageIdPage) {
		this.pageIdPage = pageIdPage;
	}

	public long getProductIdProduct() {
		return this.productIdProduct;
	}

	public void setProductIdProduct(long productIdProduct) {
		this.productIdProduct = productIdProduct;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PageProductId))
			return false;
		PageProductId castOther = (PageProductId) other;

		return (this.getPageIdPage() == castOther.getPageIdPage())
				&& (this.getProductIdProduct() == castOther
						.getProductIdProduct());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPageIdPage();
		result = 37 * result + (int) this.getProductIdProduct();
		return result;
	}

}
