package com.plip.persistance.models;

// Generated Dec 15, 2013 7:23:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ProductCategory generated by hbm2java
 */
public class ProductCategory implements java.io.Serializable {

	private long idProductType;
	private String description;
	private Set products = new HashSet(0);

	public ProductCategory() {
	}

	public ProductCategory(long idProductType) {
		this.idProductType = idProductType;
	}

	public ProductCategory(long idProductType, String description, Set products) {
		this.idProductType = idProductType;
		this.description = description;
		this.products = products;
	}

	public long getIdProductType() {
		return this.idProductType;
	}

	public void setIdProductType(long idProductType) {
		this.idProductType = idProductType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
