package com.plip.persistance.models;

// Generated Dec 15, 2013 7:23:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tray generated by hbm2java
 */
public class Tray implements java.io.Serializable {

	private long idTray;
	private Page page;
	private String code;
	private Set trayStatuses = new HashSet(0);
	private Set trayProducts = new HashSet(0);

	public Tray() {
	}

	public Tray(long idTray, Page page, String code) {
		this.idTray = idTray;
		this.page = page;
		this.code = code;
	}

	public Tray(long idTray, Page page, String code, Set trayStatuses,
			Set trayProducts) {
		this.idTray = idTray;
		this.page = page;
		this.code = code;
		this.trayStatuses = trayStatuses;
		this.trayProducts = trayProducts;
	}

	public long getIdTray() {
		return this.idTray;
	}

	public void setIdTray(long idTray) {
		this.idTray = idTray;
	}

	public Page getPage() {
		return this.page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Set getTrayStatuses() {
		return this.trayStatuses;
	}

	public void setTrayStatuses(Set trayStatuses) {
		this.trayStatuses = trayStatuses;
	}

	public Set getTrayProducts() {
		return this.trayProducts;
	}

	public void setTrayProducts(Set trayProducts) {
		this.trayProducts = trayProducts;
	}

}
