package com.plip.persistence.model;

// Generated Dec 26, 2013 8:22:22 PM by Hibernate Tools 4.0.0

/**
 * Image generated by hbm2java
 */
public class Image implements java.io.Serializable {

	private Long idImage;
	private Product product;
	private Position position;
	private String path;
	private String name;
	private byte[] descriptor;
	private boolean trained;

	public Image() {
	}

	public Image(Product product, Position position, String path,
			byte[] descriptor, boolean trained) {
		this.product = product;
		this.position = position;
		this.path = path;
		this.descriptor = descriptor;
		this.trained = trained;
	}

	public Image(Product product, String path, String name,Position position, 
			byte[] descriptor, boolean trained) {
		this.product = product;
		this.position = position;
		this.path = path;
		this.name = name;
		this.descriptor = descriptor;
		this.trained = trained;
	}
	

	public boolean validate(){
		if( product!=null && position!=null && path!=null && descriptor!=null){
			return true;
		}else return false;
	}
	
	public Long getIdImage() {
		return this.idImage;
	}

	public void setIdImage(Long idImage) {
		this.idImage = idImage;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Position getPosition() {
		return this.position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public byte[] getDescriptor() {
		return this.descriptor;
	}

	public void setDescriptor(byte[] descriptor) {
		this.descriptor = descriptor;
	}

	public boolean isTrained() {
		return this.trained;
	}

	public void setTrained(boolean trained) {
		this.trained = trained;
	}
	
	public boolean equals(Object obj) {
	      if (obj == null) return false;
	      if (!this.getClass().equals(obj.getClass())) return false;

	      Image obj2 = (Image)obj;
	      if((this.idImage == obj2.getIdImage()) && (this.name.equals(obj2.getName())))
	      {
	         return true;
	      }
	      return false;
	   }
	   public int hashCode() {
	      int tmp = 0;
	      tmp = ( idImage + name ).hashCode();
	      return tmp;
	   }
}
