package com.plip.persistence.model;

// Generated Dec 26, 2013 6:25:52 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Long idOrders;
	private String code;
	private Date insertDate;
	private String client;

	public Order() {
	}

	public Order(String code, Date insertDate, String client) {
		this.code = code;
		this.insertDate = insertDate;
		this.client = client;
	}

	public Long getIdOrders() {
		return this.idOrders;
	}

	public void setIdOrders(Long idOrders) {
		this.idOrders = idOrders;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public String getClient() {
		return this.client;
	}

	public void setClient(String client) {
		this.client = client;
	}

}
