package com.plip.persistence.model;

// Generated Dec 26, 2013 6:25:52 PM by Hibernate Tools 4.0.0

/**
 * PageImage generated by hbm2java
 */
public class PageImage implements java.io.Serializable {

	private Long idPageImage;
	private String path;

	public PageImage() {
	}

	public PageImage(String path) {
		this.path = path;
	}

	public Long getIdPageImage() {
		return this.idPageImage;
	}

	public void setIdPageImage(Long idPageImage) {
		this.idPageImage = idPageImage;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

}
