package com.plip.persistence.model;

// Generated Dec 26, 2013 6:25:52 PM by Hibernate Tools 4.0.0

/**
 * PageProduct generated by hbm2java
 */
public class PageProduct implements java.io.Serializable {

	private Long idPageProduct;
	private long idPage;
	private long idProduct;
	private int quantity;

	public PageProduct() {
	}

	public PageProduct(long idPage, long idProduct, int quantity) {
		this.idPage = idPage;
		this.idProduct = idProduct;
		this.quantity = quantity;
	}

	public Long getIdPageProduct() {
		return this.idPageProduct;
	}

	public void setIdPageProduct(Long idPageProduct) {
		this.idPageProduct = idPageProduct;
	}

	public long getIdPage() {
		return this.idPage;
	}

	public void setIdPage(long idPage) {
		this.idPage = idPage;
	}

	public long getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(long idProduct) {
		this.idProduct = idProduct;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
