package com.plip.persistence.model;

// Generated Dec 26, 2013 7:09:50 PM by Hibernate Tools 4.0.0

/**
 * PageProduct generated by hbm2java
 */
public class PageProduct implements java.io.Serializable {

	private Long idPageProduct;
	private Product product;
	private Page page;
	private int quantity;

	public PageProduct() {
	}

	public PageProduct(Product product, Page page, int quantity) {
		this.product = product;
		this.page = page;
		this.quantity = quantity;
	}

	public Long getIdPageProduct() {
		return this.idPageProduct;
	}

	public void setIdPageProduct(Long idPageProduct) {
		this.idPageProduct = idPageProduct;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Page getPage() {
		return this.page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
