package com.plip.persistence.model;

// Generated Dec 26, 2013 6:25:52 PM by Hibernate Tools 4.0.0

/**
 * Page generated by hbm2java
 */
public class Page implements java.io.Serializable {

	private Long idPage;
	private long idOrder;
	private Integer productQuantity;
	private long idPageImage;
	private int pageNumber;

	public Page() {
	}

	public Page(long idOrder, long idPageImage, int pageNumber) {
		this.idOrder = idOrder;
		this.idPageImage = idPageImage;
		this.pageNumber = pageNumber;
	}

	public Page(long idOrder, Integer productQuantity, long idPageImage,
			int pageNumber) {
		this.idOrder = idOrder;
		this.productQuantity = productQuantity;
		this.idPageImage = idPageImage;
		this.pageNumber = pageNumber;
	}

	public Long getIdPage() {
		return this.idPage;
	}

	public void setIdPage(Long idPage) {
		this.idPage = idPage;
	}

	public long getIdOrder() {
		return this.idOrder;
	}

	public void setIdOrder(long idOrder) {
		this.idOrder = idOrder;
	}

	public Integer getProductQuantity() {
		return this.productQuantity;
	}

	public void setProductQuantity(Integer productQuantity) {
		this.productQuantity = productQuantity;
	}

	public long getIdPageImage() {
		return this.idPageImage;
	}

	public void setIdPageImage(long idPageImage) {
		this.idPageImage = idPageImage;
	}

	public int getPageNumber() {
		return this.pageNumber;
	}

	public void setPageNumber(int pageNumber) {
		this.pageNumber = pageNumber;
	}

}
