package com.plip.persistence.model;

// Generated Jan 25, 2014 5:33:45 PM by Hibernate Tools 4.0.0

/**
 * PlipUser generated by hbm2java
 */
public class PlipUser implements java.io.Serializable {

	private Long idPlipUser;
	private PlipRole plipRole;
	private String name;
	private String lastName;
	private String username;
	private String password;

	public PlipUser() {
	}

	public PlipUser(PlipRole plipRole, String name, String lastName,
			String username, String password) {
		this.plipRole = plipRole;
		this.name = name;
		this.lastName = lastName;
		this.username = username;
		this.password = password;
	}

	public Long getIdPlipUser() {
		return this.idPlipUser;
	}

	public void setIdPlipUser(Long idPlipUser) {
		this.idPlipUser = idPlipUser;
	}

	public PlipRole getPlipRole() {
		return this.plipRole;
	}

	public void setPlipRole(PlipRole plipRole) {
		this.plipRole = plipRole;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	public boolean validate(){
		if(name != null && lastName != null && username != null && password != null && plipRole != null){
			return true;
		}else return false;
	}


}
