package com.plip.persistence.model;

// Generated Jan 25, 2014 5:33:45 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * PlipRole generated by hbm2java
 */
public class PlipRole implements java.io.Serializable {

	private Long idPlipRole;
	private String name;
	private String description;
	private Set plipUsers = new HashSet(0);

	public PlipRole() {
	}

	public PlipRole(String name) {
		this.name = name;
	}

	public PlipRole(String name, String description, Set plipUsers) {
		this.name = name;
		this.description = description;
		this.plipUsers = plipUsers;
	}

	public Long getIdPlipRole() {
		return this.idPlipRole;
	}

	public void setIdPlipRole(Long idPlipRole) {
		this.idPlipRole = idPlipRole;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getPlipUsers() {
		return this.plipUsers;
	}

	public void setPlipUsers(Set plipUsers) {
		this.plipUsers = plipUsers;
	}

	public boolean validate(){
		if(name!=null){
			return true;
		}else return false;
	}


}
