package com.plip.persistence.model;

// Generated Dec 26, 2013 6:25:52 PM by Hibernate Tools 4.0.0

/**
 * PlipUser generated by hbm2java
 */
public class PlipUser implements java.io.Serializable {

	private Long idPlipUser;
	private String name;
	private String lastName;
	private String username;
	private String password;
	private int idPlipRole;

	public PlipUser() {
	}

	public PlipUser(String name, String lastName, String username,
			String password, int idPlipRole) {
		this.name = name;
		this.lastName = lastName;
		this.username = username;
		this.password = password;
		this.idPlipRole = idPlipRole;
	}

	public Long getIdPlipUser() {
		return this.idPlipUser;
	}

	public void setIdPlipUser(Long idPlipUser) {
		this.idPlipUser = idPlipUser;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getIdPlipRole() {
		return this.idPlipRole;
	}

	public void setIdPlipRole(int idPlipRole) {
		this.idPlipRole = idPlipRole;
	}

}
