package com.plip.persistence.model;

// Generated Dec 26, 2013 6:25:52 PM by Hibernate Tools 4.0.0

/**
 * Position generated by hbm2java
 */
public class Position implements java.io.Serializable {

	private Integer idPosition;
	private int face;
	private int angle;

	public Position() {
	}

	public Position(int face, int angle) {
		this.face = face;
		this.angle = angle;
	}

	public Integer getIdPosition() {
		return this.idPosition;
	}

	public void setIdPosition(Integer idPosition) {
		this.idPosition = idPosition;
	}

	public int getFace() {
		return this.face;
	}

	public void setFace(int face) {
		this.face = face;
	}

	public int getAngle() {
		return this.angle;
	}

	public void setAngle(int angle) {
		this.angle = angle;
	}

}
