package com.plip.persistence.model;

// Generated Dec 26, 2013 6:25:52 PM by Hibernate Tools 4.0.0

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Long idProduct;
	private String name;
	private Integer weight;
	private String description;
	private int code;
	private String laboratory;
	private long idProductCategory;
	private Integer imageNumber;
	private boolean habilitado;

	public Product() {
	}

	public Product(String name, String description, int code,
			String laboratory, long idProductCategory, boolean habilitado) {
		this.name = name;
		this.description = description;
		this.code = code;
		this.laboratory = laboratory;
		this.idProductCategory = idProductCategory;
		this.habilitado = habilitado;
	}

	public Product(String name, Integer weight, String description, int code,
			String laboratory, long idProductCategory, Integer imageNumber,
			boolean habilitado) {
		this.name = name;
		this.weight = weight;
		this.description = description;
		this.code = code;
		this.laboratory = laboratory;
		this.idProductCategory = idProductCategory;
		this.imageNumber = imageNumber;
		this.habilitado = habilitado;
	}

	public Long getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(Long idProduct) {
		this.idProduct = idProduct;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getCode() {
		return this.code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	public String getLaboratory() {
		return this.laboratory;
	}

	public void setLaboratory(String laboratory) {
		this.laboratory = laboratory;
	}

	public long getIdProductCategory() {
		return this.idProductCategory;
	}

	public void setIdProductCategory(long idProductCategory) {
		this.idProductCategory = idProductCategory;
	}

	public Integer getImageNumber() {
		return this.imageNumber;
	}

	public void setImageNumber(Integer imageNumber) {
		this.imageNumber = imageNumber;
	}

	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

}
