package com.plip.persistence.model;

// Generated Dec 26, 2013 6:25:52 PM by Hibernate Tools 4.0.0

/**
 * ProductCategory generated by hbm2java
 */
public class ProductCategory implements java.io.Serializable {

	private Long idProductType;
	private String description;

	public ProductCategory() {
	}

	public ProductCategory(String description) {
		this.description = description;
	}

	public Long getIdProductType() {
		return this.idProductType;
	}

	public void setIdProductType(Long idProductType) {
		this.idProductType = idProductType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
