package com.plip.persistence.model;

// Generated Jan 25, 2014 5:33:45 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status implements java.io.Serializable {

	private Long idStatus;
	private String description;
	private Set trayStatuses = new HashSet(0);
	
	public final static int STATUS_TRAY_ARRAIVAL = 1;
	public final static int STATUS_TRAY_QUANTITY_EXCEEDED = 2;
	public final static int STATUS_TRAY_COUNTED = 3;
	public final static int STATUS_VALID_QUANTITY = 4;
	public final static int STATUS_INVALID_QUANTITY = 5;
	public final static int STATUS_PRODUCT_RECOGNIZED = 6;
	public final static int STATUS_PRODUCT_NOT_RECOGNIZED = 7;
	public final static int STATUS_VALID_TRAY = 8;
	public final static int STATUS_INVALID_TRAY = 9;

	public Status() {
	}

	public Status(String description) {
		this.description = description;
	}

	public Status(String description, Set trayStatuses) {
		this.description = description;
		this.trayStatuses = trayStatuses;
	}

	public Long getIdStatus() {
		return this.idStatus;
	}

	public void setIdStatus(Long idStatus) {
		this.idStatus = idStatus;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getTrayStatuses() {
		return this.trayStatuses;
	}

	public void setTrayStatuses(Set trayStatuses) {
		this.trayStatuses = trayStatuses;
	}
	
	public boolean validate(){
		if(description != null){
			return true;
		}else return false;
	}


}
