package com.plip.persistence.model;

// Generated Jan 25, 2014 5:33:45 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TrayStatus generated by hbm2java
 */
public class TrayStatus implements java.io.Serializable {

	private Long idTrayStatus;
	private Product product;
	private Tray tray;
	private Status status;
	private Integer quantity;
	private Date date;

	public TrayStatus() {
	}

	public TrayStatus(Tray tray, Status status, Date date) {
		this.tray = tray;
		this.status = status;
		this.date = date;
	}

	public TrayStatus(Product product, Tray tray, Status status,
			Integer quantity, Date date) {
		this.product = product;
		this.tray = tray;
		this.status = status;
		this.quantity = quantity;
		this.date = date;
	}

	public Long getIdTrayStatus() {
		return this.idTrayStatus;
	}

	public void setIdTrayStatus(Long idTrayStatus) {
		this.idTrayStatus = idTrayStatus;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Tray getTray() {
		return this.tray;
	}

	public void setTray(Tray tray) {
		this.tray = tray;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
	
	public boolean validate(){
		if(tray != null && status != null && date != null){
			return true;
		}else return false;
	}


}
