package com.plip.persistence.model;

// Generated Dec 26, 2013 6:25:52 PM by Hibernate Tools 4.0.0

/**
 * Tray generated by hbm2java
 */
public class Tray implements java.io.Serializable {

	private Long idTray;
	private String code;
	private long pageIdPage;

	public Tray() {
	}

	public Tray(String code, long pageIdPage) {
		this.code = code;
		this.pageIdPage = pageIdPage;
	}

	public Long getIdTray() {
		return this.idTray;
	}

	public void setIdTray(Long idTray) {
		this.idTray = idTray;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public long getPageIdPage() {
		return this.pageIdPage;
	}

	public void setPageIdPage(long pageIdPage) {
		this.pageIdPage = pageIdPage;
	}

}
