package com.plip.persistence.model;

// Generated Dec 26, 2013 6:25:52 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TrayStatus generated by hbm2java
 */
public class TrayStatus implements java.io.Serializable {

	private Long idTrayStatus;
	private long idTray;
	private int idStatus;
	private Integer quantity;
	private Long idProduct;
	private Date date;

	public TrayStatus() {
	}

	public TrayStatus(long idTray, int idStatus) {
		this.idTray = idTray;
		this.idStatus = idStatus;
	}

	public TrayStatus(long idTray, int idStatus, Integer quantity,
			Long idProduct, Date date) {
		this.idTray = idTray;
		this.idStatus = idStatus;
		this.quantity = quantity;
		this.idProduct = idProduct;
		this.date = date;
	}

	public Long getIdTrayStatus() {
		return this.idTrayStatus;
	}

	public void setIdTrayStatus(Long idTrayStatus) {
		this.idTrayStatus = idTrayStatus;
	}

	public long getIdTray() {
		return this.idTray;
	}

	public void setIdTray(long idTray) {
		this.idTray = idTray;
	}

	public int getIdStatus() {
		return this.idStatus;
	}

	public void setIdStatus(int idStatus) {
		this.idStatus = idStatus;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Long getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(Long idProduct) {
		this.idProduct = idProduct;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
